development:
  adapter: postgresql
  encoding: unicode
  database: the_game_about_nothing_development
  pool: 5
  username: the_game_about_nothing
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: the_game_about_nothing_test
  pool: 5
  username: the_game_about_nothing
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: the_game_about_nothing
  pool: 5
  username: the_game_about_nothing
  password:
